### ISSUE TITLE
Latest version linked to competition page cant load assets.

### ISSUE THREAD

**Issue by 2rsvold** [sandsmark/kart#24]
When running "kart.exe" if fails with the following error:

> kartering 3a51c90 launching...
> The Winsock 2.2 dll was found okay
> SDL error while loading BMP font.bmp: Couldn't open assets/font.bmp failed to load font
> SDL error while loading BMP background.bmp: Couldn't open assets/background.bmp unable to initialize custom rendering

The assets are located relative to kart.exe as accepted, but still get this error.

**Comment by sandsmark** [comment]
can you try to redownload and see if it works?

**Comment by 2rsvold** [comment]
Works!
